from app.database.source_crud import create_source





SOURCES = [

    # ======================================================
    # TÜRKİYE
    # ======================================================

    {
        "name": "Motor1 Türkiye",
        "website": "https://tr.motor1.com",
        "rss_url": "https://tr.motor1.com/rss/news/all/",
        "scraper": "Motor1TR",
        "language": "tr",
        "country": "Türkiye",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "Araba Haber",
        "website": "https://www.arabahaber.com",
        "rss_url": "https://www.arabahaber.com/feed/",
        "scraper": "RSS",
        "enabled": False,
        "language": "tr",
        "country": "Türkiye",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "Otoajanda",
        "website": "https://www.otoajanda.com",
        "rss_url": "https://www.otoajanda.com/feed/",
        "scraper": "RSS",
        "language": "tr",
        "country": "Türkiye",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "LOG Otomobil",
        "website": "https://www.log.com.tr",
        "rss_url": "",
        "scraper": "RSS",
        "language": "tr",
        "country": "Türkiye",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    # ======================================================
    # GLOBAL
    # ======================================================

    {
        "name": "Motor1",
        "website": "https://www.motor1.com",
        "rss_url": "https://www.motor1.com/rss/news/all/",
        "scraper": "RSS",
        "language": "en",
        "country": "Global",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "Carscoops",
        "website": "https://www.carscoops.com",
        "rss_url": "https://www.carscoops.com/feed/",
        "scraper": "RSS",
        "language": "en",
        "country": "Global",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "InsideEVs",
        "website": "https://insideevs.com",
        "rss_url": "https://insideevs.com/rss/news/",
        "scraper": "RSS",
        "language": "en",
        "country": "Global",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "Electrek",
        "website": "https://electrek.co",
        "rss_url": "https://electrek.co/feed/",
        "scraper": "RSS",
        "language": "en",
        "country": "Global",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "Autoblog",
        "website": "https://www.autoblog.com",
        "rss_url": "https://www.autoblog.com/rss.xml",
        "scraper": "RSS",
        "language": "en",
        "country": "Global",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "Auto Express",
        "website": "https://www.autoexpress.co.uk",
        "rss_url": "",
        "scraper": "AutoExpress",
        "language": "en",
        "country": "UK",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "CarBuzz",
        "website": "https://carbuzz.com",
        "rss_url": "https://carbuzz.com/rss",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    # ======================================================
    # CHINA - EDITORIAL
    # ======================================================

    {
        "name": "CarNewsChina",
        "website": "https://carnewschina.com",
        "rss_url": "https://carnewschina.com/feed/",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "CnEVPost",
        "website": "https://cnevpost.com",
        "rss_url": "https://cnevpost.com/feed/",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    {
        "name": "Gasgoo China Auto",
        "website": "https://autonews.gasgoo.com",
        "rss_url": "https://autonews.gasgoo.com/api/rss?ClassId=17",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "editorial",
        "brand": None,
        "is_oem": False,
    },

    # ======================================================
    # OEM - OFFICIAL NEWSROOMS
    # ======================================================
        {
        "name": "Toyota Global Newsroom",
        "website": "https://global.toyota",
        "rss_url": "https://global.toyota/export/en/allnews_rss.xml",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Toyota",
        "is_oem": True,
    },

    {
        "name": "Lexus Newsroom",
        "website": "https://global.toyota/en/newsroom/lexus/",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Lexus",
        "is_oem": True,
    },

    {
        "name": "Honda Global News",
        "website": "https://global.honda",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Honda",
        "is_oem": True,
    },

    {
        "name": "Nissan Newsroom",
        "website": "https://global.nissannews.com",
        "rss_url": "https://global.nissannews.com/ja-JP/rss",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Nissan",
        "is_oem": True,
    },

    {
        "name": "Mazda Newsroom",
        "website": "https://news.mazdausa.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Mazda",
        "is_oem": True,
    },

    {
        "name": "Subaru News",
        "website": "https://media.subaru.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Subaru",
        "is_oem": True,
    },

    {
        "name": "Mitsubishi News",
        "website": "https://www.mitsubishi-motors.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Mitsubishi",
        "is_oem": True,
    },

    {
        "name": "Suzuki Global News",
        "website": "https://www.globalsuzuki.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Suzuki",
        "is_oem": True,
    },

    {
        "name": "Hyundai Newsroom",
        "website": "https://www.hyundainews.com",
        "rss_url": "https://www.hyundainews.com/rss",
        "scraper": "RSS",
        "language": "en",
        "country": "Korea",
        "source_type": "oem",
        "brand": "Hyundai",
        "is_oem": True,
    },

    {
        "name": "Kia Global Media",
        "website": "https://worldwide.kia.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Korea",
        "source_type": "oem",
        "brand": "Kia",
        "is_oem": True,
    },

    {
        "name": "Genesis Newsroom",
        "website": "https://news.genesis.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Korea",
        "source_type": "oem",
        "brand": "Genesis",
        "is_oem": True,
    },

    {
        "name": "BYD News",
        "website": "https://www.byd.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "BYD",
        "is_oem": True,
    },

    {
        "name": "Chery News",
        "website": "https://www.cheryinternational.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Chery",
        "is_oem": True,
    },

    {
        "name": "Geely News",
        "website": "https://global.geely.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Geely",
        "is_oem": True,
    },

    {
        "name": "Zeekr Newsroom",
        "website": "https://www.zeekrglobal.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Zeekr",
        "is_oem": True,
    },

    {
        "name": "Volvo Cars Media",
        "website": "https://www.media.volvocars.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Sweden",
        "source_type": "oem",
        "brand": "Volvo",
        "is_oem": True,
    },

    {
        "name": "Polestar News",
        "website": "https://media.polestar.com",
        "rss_url": "https://media.polestar.com/rss",
        "scraper": "RSS",
        "language": "en",
        "country": "Sweden",
        "source_type": "oem",
        "brand": "Polestar",
        "is_oem": True,
    },

    {
        "name": "BMW Group Press",
        "website": "https://www.press.bmwgroup.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Germany",
        "source_type": "oem",
        "brand": "BMW",
        "is_oem": True,
    },

    {
        "name": "MINI Press",
        "website": "https://www.press.bmwgroup.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Germany",
        "source_type": "oem",
        "brand": "MINI",
        "is_oem": True,
    },

    {
        "name": "Mercedes-Benz Media",
        "website": "https://media.mercedes-benz.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Germany",
        "source_type": "oem",
        "brand": "Mercedes-Benz",
        "is_oem": True,
    },

    {
        "name": "Audi MediaCenter",
        "website": "https://www.audi-mediacenter.com",
        "rss_url": "https://www.audi.com/en/feeds/press-releases",
        "scraper": "RSS",
        "language": "en",
        "country": "Germany",
        "source_type": "oem",
        "brand": "Audi",
        "is_oem": True,
    },

    {
        "name": "Volkswagen Newsroom",
        "website": "https://www.volkswagen-newsroom.com",
        "rss_url": "https://www.volkswagen-newsroom.com/en/feeds/press-releases",
        "scraper": "RSS",
        "language": "en",
        "country": "Germany",
        "source_type": "oem",
        "brand": "Volkswagen",
        "is_oem": True,
    },

    {
        "name": "Porsche Newsroom",
        "website": "https://newsroom.porsche.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Germany",
        "source_type": "oem",
        "brand": "Porsche",
        "is_oem": True,
    },

    {
        "name": "Skoda Storyboard",
        "website": "https://www.skoda-storyboard.com",
        "rss_url": "https://www.skoda-storyboard.com/en/feed/",
        "scraper": "RSS",
        "language": "en",
        "country": "Czech Republic",
        "source_type": "oem",
        "brand": "Skoda",
        "is_oem": True,
    },

    {
        "name": "SEAT Media",
        "website": "https://www.seat-mediacenter.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Spain",
        "source_type": "oem",
        "brand": "SEAT",
        "is_oem": True,
    },

    {
        "name": "CUPRA Media",
        "website": "https://www.cupraofficial.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Spain",
        "source_type": "oem",
        "brand": "CUPRA",
        "is_oem": True,
    },

    {
        "name": "Renault Group News",
        "website": "https://media.renault.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "France",
        "source_type": "oem",
        "brand": "Renault",
        "is_oem": True,
    },

    {
        "name": "Dacia Media",
        "website": "https://media.renault.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Romania",
        "source_type": "oem",
        "brand": "Dacia",
        "is_oem": True,
    },

    {
        "name": "Peugeot Media",
        "website": "https://int-media.peugeot.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "France",
        "source_type": "oem",
        "brand": "Peugeot",
        "is_oem": True,
    },

    {
        "name": "Citroen Media",
        "website": "https://int-media.citroen.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "France",
        "source_type": "oem",
        "brand": "Citroen",
        "is_oem": True,
    },

    {
        "name": "Opel Media",
        "website": "https://int-media.opel.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Germany",
        "source_type": "oem",
        "brand": "Opel",
        "is_oem": True,
    },

    {
        "name": "Fiat Press",
        "website": "https://www.media.stellantis.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Italy",
        "source_type": "oem",
        "brand": "Fiat",
        "is_oem": True,
    },

    {
        "name": "Alfa Romeo Press",
        "website": "https://www.media.stellantis.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Italy",
        "source_type": "oem",
        "brand": "Alfa Romeo",
        "is_oem": True,
    },

    {
        "name": "Jeep Media",
        "website": "https://media.stellantisnorthamerica.com",
        "rss_url": "https://media.stellantisnorthamerica.com/rss.do",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Jeep",
        "is_oem": True,
    },

    {
        "name": "RAM Media",
        "website": "https://media.stellantisnorthamerica.com",
        "rss_url": "https://media.stellantisnorthamerica.com/rss.do",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "RAM",
        "is_oem": True,
    },

    {
        "name": "Dodge Media",
        "website": "https://media.stellantisnorthamerica.com",
        "rss_url": "https://media.stellantisnorthamerica.com/rss.do",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Dodge",
        "is_oem": True,
    },

    {
        "name": "Chrysler Media",
        "website": "https://media.stellantisnorthamerica.com",
        "rss_url": "https://media.stellantisnorthamerica.com/rss.do",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Chrysler",
        "is_oem": True,
    },

    {
        "name": "Maserati Media",
        "website": "https://www.media.stellantis.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Italy",
        "source_type": "oem",
        "brand": "Maserati",
        "is_oem": True,
    },

    {
        "name": "Ferrari Media Centre",
        "website": "https://media.ferrari.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Italy",
        "source_type": "oem",
        "brand": "Ferrari",
        "is_oem": True,
    },

    {
        "name": "Lamborghini News",
        "website": "https://media.lamborghini.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Italy",
        "source_type": "oem",
        "brand": "Lamborghini",
        "is_oem": True,
    },

    {
        "name": "Bentley Media",
        "website": "https://www.bentleymedia.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "UK",
        "source_type": "oem",
        "brand": "Bentley",
        "is_oem": True,
    },

    {
        "name": "Rolls-Royce Media",
        "website": "https://www.press.rolls-roycemotorcars.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "UK",
        "source_type": "oem",
        "brand": "Rolls-Royce",
        "is_oem": True,
    },

    {
        "name": "Aston Martin Media",
        "website": "https://media.astonmartin.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "UK",
        "source_type": "oem",
        "brand": "Aston Martin",
        "is_oem": True,
    },

    {
        "name": "McLaren Media",
        "website": "https://cars.mclaren.press",
        "rss_url": "https://cars.mclaren.press/rss",
        "scraper": "RSS",
        "language": "en",
        "country": "UK",
        "source_type": "oem",
        "brand": "McLaren",
        "is_oem": True,
    },

    {
        "name": "Tesla News",
        "website": "https://www.tesla.com/news",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Tesla",
        "is_oem": True,
    },

    {
        "name": "Lucid News",
        "website": "https://lucidmotors.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Lucid",
        "is_oem": True,
    },

    {
        "name": "Rivian Newsroom",
        "website": "https://stories.rivian.com",
        "rss_url": "https://stories.rivian.com/feed.rss",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Rivian",
        "is_oem": True,
    },
        {
        "name": "Ford Media Center",
        "website": "https://media.ford.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Ford",
        "is_oem": True,
    },

    {
        "name": "Lincoln Media",
        "website": "https://media.ford.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Lincoln",
        "is_oem": True,
    },

    {
        "name": "Chevrolet News",
        "website": "https://media.chevrolet.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Chevrolet",
        "is_oem": True,
    },

    {
        "name": "Cadillac News",
        "website": "https://media.cadillac.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Cadillac",
        "is_oem": True,
    },

    {
        "name": "GMC News",
        "website": "https://media.gmc.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "GMC",
        "is_oem": True,
    },

    {
        "name": "Buick News",
        "website": "https://media.buick.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "USA",
        "source_type": "oem",
        "brand": "Buick",
        "is_oem": True,
    },

    {
        "name": "Infiniti Newsroom",
        "website": "https://global.nissannews.com",
        "rss_url": "https://global.nissannews.com/ja-JP/rss",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Infiniti",
        "is_oem": True,
    },

    {
        "name": "Acura Newsroom",
        "website": "https://hondanews.com",
        "rss_url": "https://hondanews.com/en-US/rss",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Acura",
        "is_oem": True,
    },

    {
        "name": "JLR Media",
        "website": "https://media.jaguarlandrover.com",
        "rss_url": "https://media.jaguarlandrover.com/rss.xml",
        "scraper": "RSS",
        "language": "en",
        "country": "UK",
        "source_type": "oem",
        "brand": "Jaguar Land Rover",
        "is_oem": True,
    },

    {
        "name": "Jaguar Media",
        "website": "https://media.jaguarlandrover.com",
        "rss_url": "https://media.jaguarlandrover.com/rss.xml",
        "scraper": "RSS",
        "language": "en",
        "country": "UK",
        "source_type": "oem",
        "brand": "Jaguar",
        "is_oem": True,
    },

    {
        "name": "Land Rover Media",
        "website": "https://media.jaguarlandrover.com",
        "rss_url": "https://media.jaguarlandrover.com/rss.xml",
        "scraper": "RSS",
        "language": "en",
        "country": "UK",
        "source_type": "oem",
        "brand": "Land Rover",
        "is_oem": True,
    },

    {
        "name": "VinFast News",
        "website": "https://vinfastauto.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Vietnam",
        "source_type": "oem",
        "brand": "VinFast",
        "is_oem": True,
    },

    {
        "name": "NIO News",
        "website": "https://www.nio.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "NIO",
        "is_oem": True,
    },

    {
        "name": "XPENG News",
        "website": "https://www.xpeng.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "XPENG",
        "is_oem": True,
    },

    {
        "name": "Li Auto News",
        "website": "https://www.lixiang.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Li Auto",
        "is_oem": True,
    },

    {
        "name": "Great Wall Motor News",
        "website": "https://www.gwm-global.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "GWM",
        "is_oem": True,
    },

    {
        "name": "ORA News",
        "website": "https://www.gwm-global.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "ORA",
        "is_oem": True,
    },

    {
        "name": "Haval News",
        "website": "https://www.gwm-global.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Haval",
        "is_oem": True,
    },

    {
        "name": "MG Motor News",
        "website": "https://news.mgmotor.eu",
        "rss_url": "https://news.mgmotor.eu/feed/",
        "scraper": "RSS",
        "language": "en",
        "country": "UK",
        "source_type": "oem",
        "brand": "MG",
        "is_oem": True,
    },

    {
        "name": "SAIC Motor News",
        "website": "https://www.saicmotor.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "SAIC",
        "is_oem": True,
    },
        {
        "name": "Leapmotor News",
        "website": "https://www.leapmotor.net",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Leapmotor",
        "is_oem": True,
    },

    {
        "name": "AITO News",
        "website": "https://aito.auto",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "AITO",
        "is_oem": True,
    },

    {
        "name": "Avatr News",
        "website": "https://www.avatr.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Avatr",
        "is_oem": True,
    },

    {
        "name": "Deepal News",
        "website": "https://www.changan.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Deepal",
        "is_oem": True,
    },

    {
        "name": "Voyah News",
        "website": "https://www.voyah.com.cn",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Voyah",
        "is_oem": True,
    },

    {
        "name": "Hongqi News",
        "website": "https://www.faw.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Hongqi",
        "is_oem": True,
    },

    {
        "name": "FAW News",
        "website": "https://www.faw.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "FAW",
        "is_oem": True,
    },

    {
        "name": "Dongfeng News",
        "website": "https://www.dfmc.com.cn",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "Dongfeng",
        "is_oem": True,
    },

    {
        "name": "BAIC News",
        "website": "https://www.baicgroup.com.cn",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "China",
        "source_type": "oem",
        "brand": "BAIC",
        "is_oem": True,
    },

    {
        "name": "INEOS Automotive News",
        "website": "https://ineosgrenadier.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "UK",
        "source_type": "oem",
        "brand": "INEOS",
        "is_oem": True,
    },

    {
        "name": "Koenigsegg News",
        "website": "https://www.koenigsegg.com",
        "rss_url": "https://www.koenigsegg.com/rss.xml",
        "scraper": "RSS",
        "language": "en",
        "country": "Sweden",
        "source_type": "oem",
        "brand": "Koenigsegg",
        "is_oem": True,
    },

    {
        "name": "Pagani News",
        "website": "https://www.pagani.com",
        "rss_url": "https://www.pagani.com/sitemap.rss",
        "scraper": "RSS",
        "language": "en",
        "country": "Italy",
        "source_type": "oem",
        "brand": "Pagani",
        "is_oem": True,
    },

    {
        "name": "Bugatti News",
        "website": "https://newsroom.bugatti.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "France",
        "source_type": "oem",
        "brand": "Bugatti",
        "is_oem": True,
    },

    {
        "name": "Rimac News",
        "website": "https://www.rimac-automobili.com",
        "rss_url": "https://www.rimac-automobili.com/feed/",
        "scraper": "RSS",
        "language": "en",
        "country": "Croatia",
        "source_type": "oem",
        "brand": "Rimac",
        "is_oem": True,
    },

    {
        "name": "Volvo Trucks News",
        "website": "https://www.volvotrucks.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Sweden",
        "source_type": "oem",
        "brand": "Volvo Trucks",
        "is_oem": True,
    },

    {
        "name": "Scania News",
        "website": "https://www.scania.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Sweden",
        "source_type": "oem",
        "brand": "Scania",
        "is_oem": True,
    },

    {
        "name": "MAN Truck News",
        "website": "https://www.mantruckandbus.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Germany",
        "source_type": "oem",
        "brand": "MAN",
        "is_oem": True,
    },

    {
        "name": "IVECO News",
        "website": "https://www.iveco.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Italy",
        "source_type": "oem",
        "brand": "IVECO",
        "is_oem": True,
    },

    {
        "name": "DAF Trucks News",
        "website": "https://www.daf.com",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Netherlands",
        "source_type": "oem",
        "brand": "DAF",
        "is_oem": True,
    },

    {
        "name": "Isuzu News",
        "website": "https://www.isuzu.co.jp",
        "rss_url": "",
        "scraper": "RSS",
        "language": "en",
        "country": "Japan",
        "source_type": "oem",
        "brand": "Isuzu",
        "is_oem": True,
    },

]

def seed_sources():
    """
    Varsayılan haber kaynaklarını veritabanına ekler.
    """

    for source in SOURCES:
        create_source(
            name=source["name"],
            website=source["website"],
            rss_url=source["rss_url"],
            scraper=source["scraper"],
            language=source["language"],
            country=source["country"],
            source_type=source["source_type"],
            brand=source["brand"],
            is_oem=source["is_oem"],
            enabled=source.get(
                "enabled",
                (
                    bool(source["rss_url"])
                    if source["scraper"] == "RSS"
                    else True
                ),
            ),
        )
