"""initial cms update

Revision ID: 80757f2d993c
Revises: 
Create Date: 2026-07-14 20:04:03.381007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80757f2d993c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('news', sa.Column('ai_keywords', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('cover_image', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('featured', sa.Boolean(), nullable=True))
    op.add_column('news', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('is_duplicate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'is_duplicate')
    op.drop_column('news', 'views')
    op.drop_column('news', 'featured')
    op.drop_column('news', 'cover_image')
    op.drop_column('news', 'thumbnail_url')
    op.drop_column('news', 'content')
    op.drop_column('news', 'ai_confidence')
    op.drop_column('news', 'ai_keywords')
    op.drop_column('news', 'ai_model')
    # ### end Alembic commands ###
